name: Sync main to develop

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Set up SSH (if using SSH) or prepare token
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}

      - name: Fetch develop branch
        run: git fetch origin develop:develop

      - name: Checkout develop and merge main
        run: |
          git checkout develop
          git merge main --no-edit

      - name: Push changes to develop
        run: git push origin develop
